#!/bin/sh

wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/vr-radio/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/basic0/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/basic1/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/basic2/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/basic3/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/kaiwa/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/timetrial/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/enjoy/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/gendai/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/gakusyu/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/business1/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/english/business2/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/chinese/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/chinese/levelup/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/chinese/omotenashi/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/chinese/stepup/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/hangeul/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/hangeul/levelup/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/hangeul/stepup/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/italian/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/italian/kouza2/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/german/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/german/kouza2/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/french/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/french/kouza2/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/spanish/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/spanish/kouza2/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/russian/kouza/listdataflv.xml
wget -x https://cgi2.nhk.or.jp/gogaku/st/xml/russian/kouza2/listdataflv.xml
